### ISSUE TITLE
Sonoff L1 brightness

### ISSUE THREAD

**Issue by galsalman** [thepotterfamily/homebridge-ewelink-sonoff#1]
Bridge shutting down when changing the brightness.
Also color plate is not matching exactly 
For an example when asking for white it’s changing to red .

**Comment by thepotterfamily** [comment]
Sorry to hear you’re having issues.
Please elaborate...
Which sonoff device is causing the problems?
And could you share some logs with the errors so I can pinpoint the problem with the code?
Thanks!

**Comment by galsalman** [comment]
Hey, it’s the sonoff L1 led strip.
![Uploading 86406064...]()

**Comment by galsalman** [comment]
Hey,
I’m speaking about the L1 led strip 
And it seems that I can’t upload the picture .
I sent it by email.

**Comment by thepotterfamily** [comment]
> I sent it by email.

Hi I can see the email but can't open the file. Please try sending it to be bwp91@icloud.com
thanks
