### ISSUE TITLE
Server did not respond with an authentication token

### ISSUE THREAD

**Issue by ms185625** [thepotterfamily/homebridge-ewelink-sonoff#5]
**What issue do you have?**
After some recent update i'm getting startup failure on ewelink plugin
My region has 420 country code (Czechia)
I'm using mail + password auth and has no issues in the official up
**Which version of the package are you using?**
homebridge-ewelink-sonoff v1.7.7 
**Please paste any relevant logs below**
Server did not respond with an authentication token. Please double check your eWeLink username and password in the Homebridge configuration.
{
  "error": 301,
  "region": "us"
}

**Comment by thepotterfamily** [comment]
Hi,
It appears that your account is linked to the US region rather than the EU region. 
I'll look into this and get back to you.

**Comment by thepotterfamily** [comment]
Please try updating to v1.7.8 to see if this sorts this issue out.
Let me know.
Thanks

**Comment by moookino** [comment]
Thanks for the fast feedback, issue is fixed for me, have a nice weekend

**Comment by ms185625** [comment]
Issue fixed for me, thanks for the fast reply and have a nice weekend

**Comment by thepotterfamily** [comment]
Fab thank you you too.
Don’t suppose you own the sonoff fan?
I’m desperate to find someone with it for testing!

**Comment by ms185625** [comment]
no, i don't have it, only slamphers
